# Generated by Django 2.0.3 on 2018-05-07 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appearence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('lightbox', models.CharField(max_length=50)),
                ('border', models.IntegerField(default=0)),
                ('borderrad', models.IntegerField(default=0)),
                ('current', models.CharField(max_length=50)),
                ('bckgcolor', models.CharField(max_length=50)),
                ('fontcolor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='Published date')),
                ('category', models.ManyToManyField(to='webgallery.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='slider',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webgallery.Slider'),
        ),
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webgallery.Picture'),
        ),
        migrations.AddField(
            model_name='picture',
            name='slider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webgallery.Slider'),
        ),
    ]
