# Generated by Django 2.0.3 on 2018-05-15 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webgallery', '0005_auto_20180511_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('category', models.ManyToManyField(to='webgallery.Category')),
                ('pictures', models.ManyToManyField(to='webgallery.Picture')),
                ('thumbnail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Thumbnail', to='webgallery.Picture')),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.RemoveField(
            model_name='project',
            name='slider',
        ),
        migrations.RemoveField(
            model_name='project',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='picture',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
