# Generated by Django 2.0.3 on 2018-06-11 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webgallery', '0006_auto_20180515_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='date',
            new_name='creation_date',
        ),
    ]
