# Generated by Django 2.0.3 on 2018-06-11 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webgallery', '0007_auto_20180611_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='creation_date',
            new_name='date',
        ),
    ]
