# Generated by Django 2.0.3 on 2018-06-12 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webgallery', '0008_auto_20180611_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='date',
            new_name='creation_date',
        ),
    ]
