# Generated by Django 2.0.3 on 2018-07-01 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webgallery', '0009_auto_20180612_1622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'Galleries'},
        ),
    ]
