# Generated by Django 2.0.3 on 2018-07-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgallery', '0010_auto_20180701_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('marker', models.CharField(max_length=200)),
            ],
        ),
    ]
