# Generated by Django 2.0.3 on 2018-07-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgallery', '0011_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='update_date',
            field=models.DateField(auto_now=True),
        ),
    ]
